access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVVVJRCI6IjA3YTc2NjdhLTk0YmEtNDkyNC05M2QzLTNlYzk1NzgyYjMwYiIsImV4cCI6MTcyMzUwMTE1OSwiaWF0IjoxNzIzNDk3NTU5LCJpc3MiOiJib290LmRldiJ9.uj2xD053qyb2K1VKbfIX6KUNMXyFEsJjSeeHJV0zjX8
api_url: https://api.boot.dev
base_url: https://boot.dev
color:
    gray: "8"
    green: "2"
    red: "1"
last_refresh: 1723497556
refresh_token: YYjmXPwK_3Cu9wiRCG-lSpNzyU97LK_v
